baseURL = "/"
languageCode = "en-us"
title = "RnodeC"
theme = "kube"
description = "RnodeC: We are professional node operators"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "RnodeC" # add your company name
  github = "github.com/RnodeC"
  twitter = "@RnodeC"
  email = "support@Rnodec.io"


[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
