baseURL = "/"
languageCode = "en-us"
title = "RnodeC"
theme = "kube"
description = "RnodeC: We are node operators"
Paginate = 4
[Params]
  author = "RnodeC"
  github = "github.com/RnodeC"
  twitter = "@RnodeC"
  email = "support@rnodec.io"


[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
