#baseURL = "https://rnodec.io/"
languageCode = "en-us"
title = "RnodeC"
description = "Doing our duty"
theme = "hugo-ficurinia"

author = "RnodeC"
copyright = "RnodeC"

paginate = 3
summaryLength = 50

tags = false 
[params]
    author = "RnodeC"
    logo = "/logo.png"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.png"
    icon512 = "/android-chrome-512x512.png"
    enableSearch = false 
    navtype = "standard"  # or "circles"
    menuStyle = "standard" # or "buttons"
    articleSummary = true
    showSinglePageAsHome = true
    extraContentDirs = ["about"]
    homeSinglePage = "/home"
    logoRightOfTitle = true 
    imageInArticlePreview = true
    showRss = false
    showTags = false

    enableShareOnFediverse = false

    enableRelatedArticles = false
    relatedArticlesNum = 2 
    forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/RnodeC"
        weight = 10
    [[menu.icons]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/RnodeC"
        weight = 30
    [[menu.icons]]
            identifier = "discord"
            name = "Discord"
            url = "https://twitter.com/RnodeC"
            weight = 30
